server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 10.3.1.16:8848
        #group: dev
      config:
        name: gateway
        server-addr: 10.3.1.16:8848
        group: dev
    gateway:
      discovery:
        locator:
          #自动路由服务配置
          enabled: false
          lower-case-service-id: true

management:
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: gateway
logging:
  level:
    root: info